DROP TABLE IF EXISTS USER_INFORMATION;
DROP TABLE IF EXISTS USER_PASS;

CREATE TABLE USER_INFORMATION (
    id IDENTITY
    ,firstName TEXT NOT NULL
    ,lastName  TEXT NOT NULL
);

CREATE TABLE USER_PASS (
	name TEXT NOT NULL
	,pass TEXT NOT NULL
);

INSERT INTO USER_PASS VALUES('a','a')
